// wallet-store.ts — local persistence for the burner wallet generated by
// `x402-mcp init`.
//
// Storage location: ~/.config/x402-mcp/agent.json
//   File mode: 0600 (owner read/write only). The OS file permission is the
//   primary security control. We deliberately do NOT encrypt at rest:
//
//   - Threat model is "burner wallet on the developer's own machine, max
//     $5 USDC at any time". An attacker with read access to the home dir
//     already has access to enough secrets that an extra encryption layer
//     adds friction without meaningfully changing the threat surface.
//   - Encryption with a machine-id derived key gives false security (any
//     local code can derive the same key). Encryption with a passphrase
//     hurts UX (the developer types it on every MCP host start).
//   - Production agent wallets should live in OS keychain / HSM / KMS.
//     This is documented in the README.
//
// File schema:
//   {
//     "version":  2,
//     "address":  "G..." (56 chars),
//     "secret":   "S..." (56 chars, plaintext),
//     "mnemonic": "word1 word2 ... word24"  (optional, 24-word BIP39/SEP-0005 phrase)
//     "derivation_path": "m/44'/148'/0'"    (optional, only set if mnemonic is set)
//     "network":  "stellar:testnet",
//     "created_at": "2026-04-08T20:42:00.000Z",
//     "session": { "access_token": "...", "refresh_token": "..." }  (optional, set after SEP-10 handoff)
//   }

import { homedir } from "node:os";
import { join } from "node:path";
import { mkdir, readFile, writeFile, chmod, stat } from "node:fs/promises";

export interface WalletFile {
  version: number;
  address: string;
  secret: string;
  /** BIP39/SEP-0005 24-word recovery phrase. Optional for backwards compat
   *  with wallets created by older init versions. When present, Freighter
   *  can import this wallet via "Import recovery phrase". */
  mnemonic?: string;
  /** SEP-0005 derivation path. Always "m/44'/148'/0'" for the primary Stellar
   *  account, but stored explicitly so future multi-account flows are possible. */
  derivation_path?: string;
  network: string;
  created_at: string;
  session?: {
    access_token: string;
    refresh_token: string;
  };
}

const FILE_MODE = 0o600;
const DIR_MODE = 0o700;

/**
 * Returns the absolute path to the wallet file. Honors XDG_CONFIG_HOME if
 * set, otherwise defaults to ~/.config/x402-mcp/agent.json.
 */
export function walletFilePath(): string {
  const xdg = process.env.XDG_CONFIG_HOME;
  const base = xdg && xdg.length > 0 ? xdg : join(homedir(), ".config");
  return join(base, "x402-mcp", "agent.json");
}

/**
 * Saves the wallet to disk. Creates the parent directory if needed and
 * sets restrictive file permissions (0600). Overwrites any existing file.
 */
export async function saveWallet(wallet: WalletFile): Promise<string> {
  const path = walletFilePath();
  const dir = join(path, "..");
  await mkdir(dir, { recursive: true, mode: DIR_MODE });
  await writeFile(path, JSON.stringify(wallet, null, 2), { mode: FILE_MODE });
  // writeFile honors mode on creation but not on overwrite, so explicit chmod.
  await chmod(path, FILE_MODE);
  return path;
}

/**
 * Loads the wallet from disk. Returns null if the file doesn't exist or
 * fails to parse. Throws on permission errors so the developer notices.
 */
export async function loadWallet(): Promise<WalletFile | null> {
  const path = walletFilePath();
  try {
    await stat(path);
  } catch {
    return null;
  }
  const text = await readFile(path, "utf-8");
  try {
    const parsed = JSON.parse(text) as WalletFile;
    if (
      typeof parsed.address !== "string" ||
      typeof parsed.secret !== "string" ||
      typeof parsed.network !== "string"
    ) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Updates only the session field of an existing wallet file. Used after a
 * SEP-10 sign-in to persist the issued Paseto tokens alongside the wallet.
 */
export async function updateWalletSession(session: {
  access_token: string;
  refresh_token: string;
}): Promise<void> {
  const existing = await loadWallet();
  if (!existing) {
    throw new Error("no wallet file found — run `x402-mcp init` first");
  }
  existing.session = session;
  await saveWallet(existing);
}
